backend:
  name: git-gateway
media_folder: src/images
collections:
  - name: projects
    extension: json
    label: Projects
    folder: "src/content/projects"
    media_folder: "project-icons"
    create: true
    fields:
      - { label: Project image, name: image, widget: image }
      - { label: Project Title, name: title, widget: string }
      - { label: Primary Partner, name: primary-partner, widget: string }
      - { label: Other Partners, name: other-partners, widget: string }
      - { label: Description, name: description, widget: text }
      - {
          label: Additional Description,
          name: additional-description,
          widget: markdown,
        }
      - { label: Contact Name, name: contact-name, widget: string }
      - { label: Contact Email, name: call-to-action, widget: string ,  pattern: ['(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])', "Must be a valid email"]}
