backend:
  name: git-gateway
media_folder: static/assets
public_folder: /assets
collections:
  - file: "src/pages/projects/index.md"
    name: projects
    label: Projects
    folder: projects
    create: true
    fields:
    - {label: Project image, name: image, widget: image}
    - {label: Project Title, name: title, widget: string}
    - {label: Primary Partner, name: primary-partner, widget: string}
    - {label: Other Partners, name: other-partners, widget: string}
    - {label: Description, name: description, widget: string}
    - {label: Additional Description, name: additional-description, widget: string}
    - {label: Call to action, name: call-to-action, widget: string}