backend:
  name: git-gateway
media_folder: src/content/images
collections:
  - name: projects
    extension: json
    label: Projects
    folder: "src/content/projects"
    media_folder: "project-icons"
    create: true
    fields:
      - { label: Project image, name: image, widget: image }
      - { label: Project Title, name: title, widget: string }
      - { label: Primary Partner, name: primary-partner, widget: string }
      - { label: Other Partners, name: other-partners, widget: string }
      - { label: Description, name: description, widget: text }
      - {
          label: Additional Description,
          name: additional-description,
          widget: markdown,
        }
      - { label: Contact Call to Action, name: call-to-action, widget: string }
