backend:
  name: git-gateway

# when using the default proxy server port
local_backend: false
media_folder: src/content/
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Index Page"
        name: "index"
        extension: json
        file: "src/content/index.json"
        media_folder: images
        fields:
          - { label: Site Title Image, name: site-title-image, widget: image }
          - { label: Description, name: site-description, widget: string }
          - {
              label: Additional Description,
              name: site-additional-description,
              widget: string,
            }
          - label: Story Blocks
            name: stories
            widget: list
            fields:
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  default: " ",
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Full Text Description,
                  name: full-text,
                  hint: "Use this field for the larger blocks that need formatted text",
                  widget: markdown,
                  default: "",
                  required: false,
                }
          - label: Our Vision Story Blocks
            name: expanded-stories
            widget: list
            fields:
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  default: " ",
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Image Alt Text,
                  hint: "an accessible description of the image for when the image dosen't show or someone is using a screen reader",
                  name: alt-text,
                  widget: string,
                  default: "illustration of the content",
                }

              - {
                  label: Full Text Description,
                  name: full-text,
                  hint: "Use this field for the larger blocks that need formatted text",
                  widget: markdown,
                  default: "",
                  required: false,
                }
              # - {
              #     label: "Image on the Right?",
              #     name: "imageRight",
              #     hint: "If enabled, this block will have it's image on the right side of text vs left",
              #     widget: "boolean",
              #     default: false,
              #   }
          - label: Four Column Block
            name: four-column-block
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Image1, name: image1, widget: image }
              - { label: Image2, name: image2, widget: image }
              - { label: Image3, name: image3, widget: image }
              - { label: Image4, name: image4, widget: image }
              - { label: Description1, name: description1, widget: string }
              - { label: Description2, name: description2, widget: string }
              - { label: Description3, name: description3, widget: string }
              - { label: Description4, name: description4, widget: string }
              - {
                  label: Contact Call to Action,
                  hint: "e.g.: For more information about FoodLab Chicago, contact Nedra Sims at nedra@greaterchathaminitiative.org.",
                  name: call-to-action,
                  widget: string,
                }
          - label: Projects
            name: projects
            folder: "src/content/projects"
            media_folder: "project-icons"
            public_folder: "project-icons"
            widget: list
            fields:
              - {
                  label: Project Title,
                  hint: "FoodLab Chicago",
                  name: title,
                  widget: string,
                }
              - {
                  label: Project image,
                  name: image,
                  widget: image,
                  required: false,
                  default: "project-icons/light-bulb.png",
                }
              - {
                  label: Primary Partner,
                  hint: "Greater Chatham Initiative",
                  name: primary-partner,
                  widget: string,
                }
              - {
                  label: Other Partners,
                  hint: "In partnership with FoodLab Detroit, Association for Enterprise Opportunity and South Shore Chamber of Commerce.",
                  name: other-partners,
                  widget: string,
                }
              - {
                  label: Description,
                  hint: "Providing integrated services to mature food businesses owned by people of color in the South Shore and Chatham communities by addressing acute barriers that hamper their growth.",
                  name: description,
                  widget: text,
                }
              - {
                  label: Additional Description,
                  hint: "FoodLab Detroit has created an effective model for developing cohorts of industry-specialized food entrepreneurs to provide...etc",
                  name: additional-description,
                  widget: markdown,
                }
              - {
                  label: Contact Call to Action,
                  hint: "e.g.: For more information about FoodLab Chicago, contact Nedra Sims at nedra@greaterchathaminitiative.org.",
                  name: call-to-action,
                  widget: string,
                }
      - label: "Index Page Spanish"
        name: "index_es"
        extension: json
        file: "src/content/index-es.json"
        media_folder: images
        fields:
          - { label: Site Title Image, name: site-title-image, widget: image }
          - { label: Description, name: site-description, widget: string }
          - {
              label: Additional Description,
              name: site-additional-description,
              widget: string,
            }
          - label: Story Blocks
            name: stories
            widget: list
            fields:
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  default: " ",
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Full Text Description,
                  name: full-text,
                  hint: "Use this field for the larger blocks that need formatted text",
                  widget: markdown,
                  default: "",
                  required: false,
                }
          - label: Our Vision Story Blocks
            name: expanded-stories
            widget: list
            fields:
              - {
                  label: Description,
                  name: description,
                  widget: string,
                  default: " ",
                }
              - { label: Image, name: image, widget: image }
              - {
                  label: Image Alt Text,
                  hint: "an accessible description of the image for when the image dosen't show or someone is using a screen reader",
                  name: alt-text,
                  widget: string,
                  default: "illustration of the content",
                }

              - {
                  label: Full Text Description,
                  name: full-text,
                  hint: "Use this field for the larger blocks that need formatted text",
                  widget: markdown,
                  default: "",
                  required: false,
                }
              # - {
              #     label: "Image on the Right?",
              #     name: "imageRight",
              #     hint: "If enabled, this block will have it's image on the right side of text vs left",
              #     widget: "boolean",
              #     default: false,
              #   }
          - label: Four Column Block
            name: four-column-block
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Image1, name: image1, widget: image }
              - { label: Image2, name: image2, widget: image }
              - { label: Image3, name: image3, widget: image }
              - { label: Image4, name: image4, widget: image }
              - { label: Description1, name: description1, widget: string }
              - { label: Description2, name: description2, widget: string }
              - { label: Description3, name: description3, widget: string }
              - { label: Description4, name: description4, widget: string }
              - {
                  label: Contact Call to Action,
                  hint: "e.g.: For more information about FoodLab Chicago, contact Nedra Sims at nedra@greaterchathaminitiative.org.",
                  name: call-to-action,
                  widget: string,
                }
          - label: Projects
            name: projects
            folder: "src/content/projects"
            media_folder: "project-icons"
            public_folder: "project-icons"
            widget: list
            fields:
              - {
                  label: Project Title,
                  hint: "FoodLab Chicago",
                  name: title,
                  widget: string,
                }
              - {
                  label: Project image,
                  name: image,
                  widget: image,
                  required: false,
                  default: "project-icons/light-bulb.png",
                }
              - {
                  label: Primary Partner,
                  hint: "Greater Chatham Initiative",
                  name: primary-partner,
                  widget: string,
                }
              - {
                  label: Other Partners,
                  hint: "In partnership with FoodLab Detroit, Association for Enterprise Opportunity and South Shore Chamber of Commerce.",
                  name: other-partners,
                  widget: string,
                }
              - {
                  label: Description,
                  hint: "Providing integrated services to mature food businesses owned by people of color in the South Shore and Chatham communities by addressing acute barriers that hamper their growth.",
                  name: description,
                  widget: text,
                }
              - {
                  label: Additional Description,
                  hint: "FoodLab Detroit has created an effective model for developing cohorts of industry-specialized food entrepreneurs to provide...etc",
                  name: additional-description,
                  widget: markdown,
                }
              - {
                  label: Contact Call to Action,
                  hint: "e.g.: For more information about FoodLab Chicago, contact Nedra Sims at nedra@greaterchathaminitiative.org.",
                  name: call-to-action,
                  widget: string,
                }
